name: CI + Vercel Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Type Check (vue-tsc)
        run: pnpm vue-tsc --noEmit
      - name: Build
        run: pnpm build
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
